language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "Everything is ready. Nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "No tests found"

script:
  - docker --version # printing the version for logging
  - docker build -t simple-node . #building docker image
  - docker tag simple-node YOUR_DOCKER_HUB/simple-node:latest #renaming docker image

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push YOUR_DOCKER_HUB/simple-node